#!/usr/bin/env bash
# World wide web task

dom_sub_ () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    dom_sub_ "$2.$1" "$2"
else
    dom_sub_ "www.$1" "www"
    dom_sub_ "lb-01.$1" "lb-01"
    dom_sub_ "web-01.$1" "web-01"
    dom_sub_ "web-02.$1" "web-02"
fi
