#!/usr/bin/env bash
# Configuring the Nginx and HTTP response must contain a custom header

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 531269-web-01 100.25.20.183:80 check\n\tserver 531269-web-02 54.208.41.157:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
