#!/usr/bin/env bash
#Bash script that configures a server to the above requirements...

sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo service nginx restart
