#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process
#You must use kill

#lets get the pid of the file program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#Finish the infinite process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
