#!/usr/bin/env bash
#Bash script that prints Best school 10 times
#and on the 9th iteration displays Best school and then Hi
count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
